;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/notes/roam/daily/2026-02-22.org")
  (front-context-string . "* TODO another t")
  (rear-context-string . "2-22 Sun 12:55]\n")
  (position . 151)
  (last-modified 27035 27981 57288 0))
)
